# Generated by Django 4.2.4 on 2023-08-10 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
            ],
            options={
                'verbose_name': 'Ano e mês',
                'verbose_name_plural': 'Anos e meses',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Dia da compra')),
                ('compra', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('parcela_atual', models.PositiveIntegerField(default=1)),
                ('numero_de_parcelas', models.PositiveIntegerField(default=1)),
                ('ano_e_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.anomes')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.pessoa')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
