# Generated by Django 4.2.4 on 2023-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_gastosmensais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomes',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='anomes',
            unique_together={('ano', 'mes')},
        ),
    ]
