# Generated by Django 4.2.4 on 2023-08-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_gastosmensais_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gastosmensais',
            name='total_gasto',
            field=models.FloatField(default=0),
        ),
    ]
